### ISSUE TITLE
menu position when on screen edges

### ISSUE THREAD

**Issue by msarsha** [msarsha/ng2-right-click-menu#4]
When the menu is open next to the edge of the screen it will not fix it's position and part of it will be hidden.

**Comment by phsantiago** [comment]
I tested here https://msarsha.github.io/ng2-right-click-menu/ and I think this problem is already solved

**Comment by flaminestone** [comment]
No, this problem is not solved
![image](https://user-images.githubusercontent.com/6047261/32168645-8157db12-bd7e-11e7-89de-0b8ff4aa5f05.png)

**Comment by msarsha** [comment]
@flaminestone @phsantiago 

Yeah, bug still exists.

**Comment by AlexLnz** [comment]
Working on this issue ...

**Comment by msarsha** [comment]
implemented in #55
